name: Release

on:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  publish-crate:
    name: Publish to crates.io
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libavcodec-dev libavformat-dev \
                                  libavutil-dev libavfilter-dev libavdevice-dev \
                                  libswscale-dev libswresample-dev clang

      - name: Publish to crates.io
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo publish --token ${CARGO_REGISTRY_TOKEN}

  build-binaries:
    name: Build ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # Linux
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: showme
            asset_name: showme-linux-x86_64

          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            artifact_name: showme
            asset_name: showme-linux-aarch64
            cross: true

          # macOS
          - os: macos-13  # Intel runner for x86_64
            target: x86_64-apple-darwin
            artifact_name: showme
            asset_name: showme-macos-x86_64

          - os: macos-latest  # ARM runner for aarch64
            target: aarch64-apple-darwin
            artifact_name: showme
            asset_name: showme-macos-aarch64

          # Windows
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact_name: showme.exe
            asset_name: showme-windows-x86_64.exe

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install dependencies (Ubuntu)
        if: matrix.os == 'ubuntu-latest' && !matrix.cross
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libavcodec-dev libavformat-dev \
                                  libavutil-dev libavfilter-dev libavdevice-dev \
                                  libswscale-dev libswresample-dev clang

      - name: Install cross-compilation tools (Linux ARM64)
        if: matrix.cross && matrix.target == 'aarch64-unknown-linux-gnu'
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
          rustup target add aarch64-unknown-linux-gnu

      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install ffmpeg pkg-config

      # Windows: Skip ffmpeg for now (complex setup)
      # Video feature will be disabled in build step

      - name: Build (native)
        if: "!matrix.cross"
        run: |
          # Build without video feature on Windows (ffmpeg setup complex)
          if [ "${{ runner.os }}" = "Windows" ]; then
            cargo build --release --locked --target ${{ matrix.target }} --no-default-features --features unicode,kitty,iterm2,qoi,pdf,svg
          else
            cargo build --release --locked --target ${{ matrix.target }}
          fi
        shell: bash

      - name: Build (cross)
        if: matrix.cross
        run: |
          cargo install cross --git https://github.com/cross-rs/cross
          # Build without video feature for cross-compilation (ARM64 ffmpeg not readily available)
          cross build --release --locked --target ${{ matrix.target }} --no-default-features --features unicode,kitty,iterm2,qoi,pdf,svg

      - name: Strip binary (Linux/macOS)
        if: matrix.os != 'windows-latest' && !matrix.cross
        run: strip target/${{ matrix.target }}/release/${{ matrix.artifact_name }}

      - name: Create tarball (Linux/macOS)
        if: matrix.os != 'windows-latest'
        run: |
          cd target/${{ matrix.target }}/release
          tar czf ../../../${{ matrix.asset_name }}.tar.gz ${{ matrix.artifact_name }}
          cd ../../..

      - name: Create zip (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          cd target/${{ matrix.target }}/release
          7z a ../../../${{ matrix.asset_name }}.zip ${{ matrix.artifact_name }}
          cd ../../..

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.asset_name }}
          path: |
            ${{ matrix.asset_name }}.tar.gz
            ${{ matrix.asset_name }}.zip
          if-no-files-found: error

  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: [publish-crate, build-binaries]
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Generate changelog
        id: changelog
        run: |
          # Get the previous tag
          PREV_TAG=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")

          # Generate changelog from commit history
          if [ -z "$PREV_TAG" ]; then
            CHANGELOG=$(git log --pretty=format:"- %s (%h)" ${GITHUB_REF_NAME})
          else
            CHANGELOG=$(git log --pretty=format:"- %s (%h)" ${PREV_TAG}..${GITHUB_REF_NAME})
          fi

          # Save to file for multiline handling
          echo "## Changelog" > changelog.md
          echo "" >> changelog.md
          echo "$CHANGELOG" >> changelog.md
          echo "" >> changelog.md
          echo "## Platform Compatibility" >> changelog.md
          echo "" >> changelog.md
          echo "Pre-built binaries have different feature support depending on the platform:" >> changelog.md
          echo "" >> changelog.md
          echo "| Platform | Video Support | Sixel | All Other Features* |" >> changelog.md
          echo "|----------|---------------|-------|---------------------|" >> changelog.md
          echo "| **Linux x86_64** | ✅ Yes | ✅ Yes (optional) | ✅ Yes |" >> changelog.md
          echo "| **Linux ARM64** | ❌ No† | ❌ No | ✅ Yes |" >> changelog.md
          echo "| **macOS x86_64 (Intel)** | ✅ Yes | ❌ No | ✅ Yes |" >> changelog.md
          echo "| **macOS ARM64 (Apple Silicon)** | ✅ Yes | ❌ No | ✅ Yes |" >> changelog.md
          echo "| **Windows x86_64** | ❌ No‡ | ❌ No | ✅ Yes |" >> changelog.md
          echo "" >> changelog.md
          echo "*All other features include: Unicode rendering, Kitty graphics, iTerm2 images, QOI, PDF, and SVG support*" >> changelog.md
          echo "" >> changelog.md
          echo "† Linux ARM64: Cross-compilation constraints prevent video support. Build from source with ffmpeg for video." >> changelog.md
          echo "‡ Windows: Build from source with vcpkg for video support." >> changelog.md
          echo "" >> changelog.md
          echo "## Downloads" >> changelog.md
          echo "" >> changelog.md
          echo "Pre-built binaries are available for the following platforms:" >> changelog.md
          echo "" >> changelog.md
          echo "- **Linux**: \`showme-linux-x86_64.tar.gz\`, \`showme-linux-aarch64.tar.gz\`" >> changelog.md
          echo "- **macOS**: \`showme-macos-x86_64.tar.gz\`, \`showme-macos-aarch64.tar.gz\`" >> changelog.md
          echo "- **Windows**: \`showme-windows-x86_64.exe.zip\`" >> changelog.md
          echo "" >> changelog.md
          echo "Or install via cargo:" >> changelog.md
          echo "\`\`\`bash" >> changelog.md
          echo "cargo install showme" >> changelog.md
          echo "\`\`\`" >> changelog.md

          # Set output
          echo "changelog_file=changelog.md" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ github.ref_name }}
          body_path: ${{ steps.changelog.outputs.changelog_file }}
          files: |
            artifacts/**/*.tar.gz
            artifacts/**/*.zip
          token: ${{ secrets.GITHUB_TOKEN }}
